env:
 - CABALVER=1.22 GHCVER=7.10.1

before_install:
  - sudo add-apt-repository -y ppa:hvr/ghc
  - sudo apt-get update -qq
  - sudo apt-get install -qq cabal-install-$CABALVER ghc-$GHCVER
  - export PATH="/opt/cabal/$CABALVER/bin:/opt/ghc/$GHCVER/bin:$PATH"

install:
  - cabal --version
  - cabal update
  - cabal install --only-dependencies --enable-tests --enable-benchmarks

script:
  - cabal configure --enable-tests --enable-benchmarks -v2
  - cabal build
  - cabal test
  - cabal check
  - cabal sdist

after_script:
  - ghc-pkg list
