env:
 - CABALVER=1.20 GHCVER=7.8.4
 - CABALVER=1.22 GHCVER=7.10.1

matrix:
  allow_failures:
    - env: CABALVER=1.22 GHCVER=7.10.1

before_install:
  - sudo add-apt-repository -y ppa:hvr/ghc
  - sudo apt-get update -qq

install:
  - sudo apt-get install -qq cabal-install-$CABALVER ghc-$GHCVER
  - export PATH="/opt/cabal/$CABALVER/bin:/opt/ghc/$GHCVER/bin:$PATH"

before_script:
  - cabal --version
  - cabal update
  - cabal install "Cabal == $CABALVER.*"
  - cabal update
  - cabal --version
  - ghc --version
  - ghc-pkg list
  - cabal install --only-dependencies

script:
  - cabal install
  - cabal test
  - cabal sdist

after_script:
  - ghc-pkg list
