flags:
  text:
    integer-simple: false
  pandoc:
    old-locale: false
  time-locale-compat:
    old-locale: false
packages:
- '.'
extra-deps:
- HTTP-4000.2.20
- JuicyPixels-3.2.6
- QuickCheck-2.7.6
- SHA-1.6.4.2
- StateVar-1.1.0.1
- acid-state-0.12.4
- adjunctions-4.2.1
- aeson-0.9.0.1
- asn1-encoding-0.9.0
- asn1-parse-0.9.1
- asn1-types-0.3.0
- async-2.0.2
- attoparsec-0.13.0.1
- base16-bytestring-0.1.1.6
- base64-bytestring-1.0.0.1
- bifunctors-4.2.1
- blaze-builder-0.4.0.1
- blaze-html-0.8.1.0
- blaze-markup-0.7.0.2
- byteable-0.1.1
- case-insensitive-1.2.0.4
- cereal-0.4.1.1
- clock-0.5.1
- cmark-0.4.0.1
- comonad-4.2.7.2
- conduit-1.2.5
- connection-0.2.5
- contravariant-1.3.2
- cookie-0.4.1.6
- cryptohash-0.11.6
- cryptonite-0.6
- data-default-0.5.3
- data-default-class-0.0.1
- data-default-instances-base-0.0.1
- data-default-instances-containers-0.0.1
- data-default-instances-dlist-0.0.1
- data-default-instances-old-locale-0.0.1
- deepseq-generics-0.1.1.2
- digest-0.0.1.2
- distributive-0.4.4
- dlist-0.7.1.1
- double-conversion-2.0.1.0
- enclosed-exceptions-1.0.1.1
- exceptions-0.8.0.2
- extensible-exceptions-0.1.1.4
- extra-1.1
- feed-0.3.11.1
- filemanip-0.3.6.3
- formatting-6.2.2
- free-4.12.1
- haddock-library-1.2.1
- hashable-1.2.3.3
- highlighting-kate-0.6
- hourglass-0.2.9
- hslua-0.4.0
- http-client-0.4.20
- http-client-tls-0.2.2
- http-types-0.8.6
- kan-extensions-4.2.2
- lens-4.8
- lens-aeson-1.0.0.4
- lifted-base-0.2.3.6
- memory-0.8
- mime-types-0.1.0.6
- mmorph-1.0.4
- monad-control-1.0.0.4
- mtl-2.2.1
- nats-1
- network-2.6.2.1
- network-uri-2.6.0.3
- old-locale-1.0.0.7
- old-time-1.1.0.3
- pandoc-1.15.0.6
- pandoc-types-1.12.4.5
- parallel-3.2.0.6
- parsec-3.1.9
- pem-0.2.2
- pipes-4.1.6
- pipes-concurrency-2.0.3
- prelude-extras-0.4
- primitive-0.5.4.0
- profunctors-4.4.1
- psqueues-0.2.0.2
- random-1.1
- reflection-1.5.2.1
- regex-base-0.93.2
- regex-pcre-builtin-0.94.4.8.8.35
- resourcet-1.1.6
- safecopy-0.8.5
- scientific-0.3.3.8
- semigroupoids-4.3
- semigroups-0.16.2.2
- socks-0.5.4
- stm-2.4.4
- streaming-commons-0.1.12.1
- syb-0.5.1
- tagged-0.8.1
- tagsoup-0.13.3
- temporary-1.2.0.3
- texmath-0.8.3
- text-1.2.1.3
- text-format-0.3.1.1
- tf-random-0.5
- time-locale-compat-0.1.1.0
- tls-1.3.1
- transformers-base-0.4.4
- transformers-compat-0.4.0.4
- unix-compat-0.4.1.4
- unordered-containers-0.2.5.1
- utf8-string-1.0.1
- vector-0.10.12.3
- void-0.7
- vty-5.2.9
- vty-ui-1.9
- wreq-0.4.0.0
- x509-1.6.0
- x509-store-1.6.0
- x509-system-1.6.0
- x509-validation-1.6.0
- xml-1.3.14
- yaml-0.8.13
- zip-archive-0.2.3.7
- zlib-0.6.1.1
resolver: ghc-7.10.1
